spring:
  profiles:
    active: dev
    
logging:
  level:
    com.study.boot: debug 
    org.hibernate.SQL: debug #logger를 통해 출력
    org.hibernate.type: trace #SQL 쿼리 파라미터를 확인할 수 있다
    org.spring.framework.web: debug 
    org.springframework.security: debug
    
  datasource:
    url: jdbc:h2:tcp://localhost/~/security
    
    username: sa
    password: 
    driver-class-name: org.h2.Driver